### ISSUE TITLE
Mixure of absolute and relative paths in html frontend

### ISSUE THREAD

**Issue by zutroy97** [loftx/gnucash-rest#2]
I noticed the javascript/html/css files use a combination of relative and absolute paths. Could these paths be configurable or at least made relative for easier installation?

**Comment by loftx** [comment]
Hi @zutroy97,

Apologies for the delayed reply, I don't appear to be receiving emails for the issues - all paths should be absolute (I can see at least one which isn't at the moment though), though this obviously prevents installs into a subdirectory. 

I'll try and push an update to fix this one way or the other, alternatively please submit a pull request.

Thanks,

Tom

**Comment by zutroy97** [comment]
I believe I was able to get around this by using mod_substitute 

```
        <Location /gnucash >
                AddOutputFilterByType DEFLATE txt xml css js php #Deflate causes SUBSTITUTE not to work
                AddOutputFilterByType SUBSTITUTE text/html
                Substitute s|/js/|/gnucash/js/|ni
                Substitute s|/css/|/gnucash/css/|ni
                Substitute s|src="js/|src="/gnucash/js/|ni
        </Location>
```

**Comment by loftx** [comment]
Fixed by zutroy97 in https://github.com/loftx/gnucash-rest/pull/3
