### ISSUE TITLE
The date posted must be provided in the form YYYY-MM-DD

### ISSUE THREAD

**Issue by ghost** [loftx/gnucash-rest#4]
Hello there,

I'm trying to create a new transaction but I keep getting that error. The calendar helper is writting the date in the required format. What can be happening?

P.S.: Nice app!

**Comment by ghost** [comment]
Doing some debugging I found that the gnucash_rest/__init__.py receives the date_posted like this:

Sat Mar 10 2018 00:00:00 GMT-0300 (-03)

Which is not matching the spected format. I will check the web client.

**Comment by ghost** [comment]
This is the line with trouble:

https://github.com/loftx/gnucash-rest/blob/616c0ce5d124972a781f4d78ea170f9c0bf61fa2/gnucash_rest/__init__.py#L2178

**Comment by loftx** [comment]
Hi there,

Thanks for reporting this - some screens in the app have now been updated to use the bootstrap datepicker which sends dates in a different  format by default.

Ill look into this and relasese an update over the next few days.

**Comment by loftx** [comment]
Hi there,

This issue has been resolved - I should mention the accounts area is the most buggy as I haven't done much testing in this area.

If you do notice any further issues here please submit issues for them.

Thanks,

Tom

**Comment by ghost** [comment]
Thanks again, this app is very useful. I just use the "add transaction" for now.
