### ISSUE TITLE
Accounts > Add transaction: Ignoring amount field

### ISSUE THREAD

**Issue by ghost** [loftx/gnucash-rest#5]
When I create a new transaction the Charge field is 0.00. I tried integers, floats with dot and comma without luck.

**Comment by loftx** [comment]
Hi thanks for reporting this - sorry it's causing problems - there are definitely some outstanding issues in this area. Can you let me know the account type you're trying to add the transaction in and the transfer account you selected when adding the transaction?

**Comment by ghost** [comment]
No problem at all. I'm doing a transaction in the Expenses:Groceries account to Assets:Current Assets:Wallet.

I looked into the database and for some reason the currency type guid wasn't correct. Also for some reason the values are not saving in the same way when I do it with the GnuCash program.

Let me know if you need any other info.

**Comment by loftx** [comment]
Hi,

This should hopefully be resolved in the latest commit. Adding a transaction previously hardcoded the currency to GBP which will only work if your accounts use GBP as a currency which I'm guessing they don't...

Please let me know if this doesn't resolve the issue for you. Also there are still a few areas where GBP is hardcoded as a currency so if you run into this issue elsewhere or any other issues please raise them.

Thanks for helping to test this project - it's really appreciated!

**Comment by ghost** [comment]
Worked like a charm. I realized that I need to put a negative value in the Amount field to make it a charge in the assets. That is on purpose right?
