### ISSUE TITLE
Support for more than two splits

### ISSUE THREAD

**Issue by PHPBendel** [loftx/gnucash-rest#7]
> POST request to /transactions - creates a new transaction (currently with only two splits)
 
Do you have any idea of how long it would take for you to implement this?
Do you need some bounty?

**Comment by loftx** [comment]
Hi there,

This is pretty simple to implement as the underlying GnuCash APIs allow multiple splits per transaction, it's just the REST part which is has two splits hardcoded.

Is there an upper limit on the number of splits you expect to be using? Also can you let me know the version of Gnucash and Python you're using as there are certain incompatibities with the API which I'm currently looking into seperately.

I expect I can add this functionality in the next week or so.

Kind regards,

Tom

**Comment by PHPBendel** [comment]
Hi!

I'm using Python 2.7.12 and Gnucash 2.6.12. There are some cases that I could use even 7 splits. 

Thanks,

Pedro

**Comment by loftx** [comment]
Hi Pedro,

Thanks for the information you provided - I've made an update to the API so you should be able to add unlimited splits, however this only affects the REST API so far - I haven't made the corresponding changes to the user interface which will be a bit more difficult.

I'll look to pick up on the UI functionality as well if this is something you need.

Kind regards,

Tom

**Comment by PHPBendel** [comment]
It works like a charm! 
Sorry for taking so long to close the issue.

Thank you very much, Tom!

I'm only using the REST API, so i won't really miss this functionality on the UI.
